services:
  redis:
    image: redis/redis-stack-server:latest
    ports: 
      - 6379:6379
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
     - redis
     - mongo